"""README generator for output directories."""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from src.config import format_number

logger = logging.getLogger(__name__)


def export_output_readme(
    output_dir: Path, timestamp: str, channels_data: list[dict[str, Any]]
) -> None:
    """Generate README.md in output directory explaining all generated files."""
    readme_path = output_dir / "README.md"
    total_channels = len(channels_data)
    total_videos = sum(len(cd["videos"]) for cd in channels_data)
    avg_videos = total_videos / total_channels if total_channels > 0 else 0

    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(f"# YouTube Analysis Report - {timestamp}\n\n")
        f.write(f"Generated on: {datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}\n\n")

        f.write("## Analysis Summary\n\n")
        f.write(f"- **Channels Analyzed:** {total_channels}\n")
        f.write(f"- **Total Videos:** {total_videos}\n")
        f.write(f"- **Average Videos per Channel:** {avg_videos:.1f}\n\n")

        _write_file_descriptions(f, timestamp)
        _write_metrics_table(f)
        _write_channels_list(f, channels_data)

        f.write("\n---\n\n")
        f.write("*Generated by YouTube Toolkit*\n")

    logger.info("Generated README.md in output directory: %s", readme_path)


def _write_file_descriptions(f: Any, timestamp: str) -> None:
    """Write descriptions for each generated file."""
    files = [
        (
            f"youtube_channels_videos_{timestamp}.csv",
            "CSV (Comma-Separated Values)",
            "Raw data export with complete metrics for all videos.",
            ["Import into Excel/Google Sheets", "Data visualization with BI tools"],
        ),
        (
            f"youtube_channel_stats_{timestamp}.txt",
            "Plain text report",
            "Per-channel statistics, top videos, and performance distribution.",
            ["Quick overview of channel performance", "Identify content patterns"],
        ),
        (
            f"youtube_engagement_trends_{timestamp}.txt",
            "Plain text report",
            "Cross-channel comparison, rankings, and trend analysis.",
            ["Compare channels", "Discover viral content patterns"],
        ),
        (
            f"youtube_best_videos_{timestamp}.txt",
            "Plain text (URL list)",
            "Top 15 videos with highest engagement rate from each channel.",
            ["Quick access to best content", "Create playlists"],
        ),
        (
            f"youtube_latest_videos_{timestamp}.txt",
            "Plain text (URL list)",
            "15 most recent videos from each channel.",
            ["Track recent content", "Monitor channel activity"],
        ),
    ]

    f.write("## Generated Files\n\n")
    for name, fmt, desc, uses in files:
        f.write(f"### `{name}`\n")
        f.write(f"**Format:** {fmt}\n\n")
        f.write(f"**Description:** {desc}\n\n")
        f.write("**Use Cases:**\n")
        for use in uses:
            f.write(f"- {use}\n")
        f.write("\n---\n\n")


def _write_metrics_table(f: Any) -> None:
    """Write engagement metrics explanation table."""
    f.write("## Engagement Metrics Explained\n\n")
    f.write("| Metric | Formula | Interpretation |\n")
    f.write("|--------|---------|----------------|\n")
    f.write(
        "| **Engagement Rate (Views)** "
        "| `(likes + comments) / views x 100` "
        "| Audience interaction |\n"
    )
    f.write(
        "| **Engagement Rate (Subs)** "
        "| `(likes + comments) / subscribers x 100` "
        "| Relative to size |\n"
    )
    f.write("| **View Rate** | `views / subscribers x 100` | >100% = viral potential |\n")
    f.write("| **Like Rate** | `likes / views x 100` | Viewer satisfaction |\n")
    f.write("| **Comment Rate** | `comments / views x 100` | Discussion level |\n")
    f.write("| **Views per Minute** | `views / (duration / 60)` | Content efficiency |\n\n")


def _write_channels_list(f: Any, channels_data: list[dict[str, Any]]) -> None:
    """Write list of analyzed channels."""
    f.write("## Channels Analyzed\n\n")
    for i, cd in enumerate(channels_data, 1):
        info = cd["channel"]
        subs = format_number(info.get("subscriber_count"))
        count = len(cd["videos"])
        f.write(f"{i}. **{info['title']}** - {subs} subscribers ({count} videos analyzed)\n")
